# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import planner_pb2 as planner__pb2


class RoutePlannerStub(object):
  """The route planner service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PlanRoute = channel.unary_unary(
        '/RoutePlanner/PlanRoute',
        request_serializer=planner__pb2.JsonReply.SerializeToString,
        response_deserializer=planner__pb2.JsonReply.FromString,
        )


class RoutePlannerServicer(object):
  """The route planner service definition.
  """

  def PlanRoute(self, request, context):
    """Plan a route
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RoutePlannerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PlanRoute': grpc.unary_unary_rpc_method_handler(
          servicer.PlanRoute,
          request_deserializer=planner__pb2.JsonReply.FromString,
          response_serializer=planner__pb2.JsonReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RoutePlanner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
